// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/routes": {
    params: {};
  };
  "/routes/:id": {
    params: {
      "id": string;
    };
  };
  "/bookings": {
    params: {};
  };
  "/tracking": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/fees": {
    params: {};
  };
  "/fees/:id/pay": {
    params: {
      "id": string;
    };
  };
  "/fees/payment-history": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/routes" | "/routes/:id" | "/bookings" | "/tracking" | "/profile" | "/fees" | "/fees/:id/pay" | "/fees/payment-history" | "/notifications" | "/settings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/routes-list.tsx": {
    id: "routes/routes-list";
    page: "/routes";
  };
  "routes/route-details.tsx": {
    id: "routes/route-details";
    page: "/routes/:id";
  };
  "routes/bookings.tsx": {
    id: "routes/bookings";
    page: "/bookings";
  };
  "routes/tracking.tsx": {
    id: "routes/tracking";
    page: "/tracking";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/fees._index.tsx": {
    id: "routes/fees._index";
    page: "/fees";
  };
  "routes/fees.$id.pay.tsx": {
    id: "routes/fees.$id.pay";
    page: "/fees/:id/pay";
  };
  "routes/payment-history.tsx": {
    id: "routes/payment-history";
    page: "/fees/payment-history";
  };
  "routes/notifications.tsx": {
    id: "routes/notifications";
    page: "/notifications";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/routes-list": typeof import("./app/routes/routes-list.tsx");
  "routes/route-details": typeof import("./app/routes/route-details.tsx");
  "routes/bookings": typeof import("./app/routes/bookings.tsx");
  "routes/tracking": typeof import("./app/routes/tracking.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/fees._index": typeof import("./app/routes/fees._index.tsx");
  "routes/fees.$id.pay": typeof import("./app/routes/fees.$id.pay.tsx");
  "routes/payment-history": typeof import("./app/routes/payment-history.tsx");
  "routes/notifications": typeof import("./app/routes/notifications.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
};