// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/route": {
    params: {};
  };
  "/bus": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/trips": {
    params: {};
  };
  "/trip/history": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/route" | "/bus" | "/profile" | "/notifications" | "/trips" | "/trip/history" | "/settings";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/route.tsx": {
    id: "routes/route";
    page: "/route";
  };
  "routes/bus.tsx": {
    id: "routes/bus";
    page: "/bus";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/notifications.tsx": {
    id: "routes/notifications";
    page: "/notifications";
  };
  "routes/trips.tsx": {
    id: "routes/trips";
    page: "/trips";
  };
  "routes/trip/history.tsx": {
    id: "routes/trip/history";
    page: "/trip/history";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/route": typeof import("./app/routes/route.tsx");
  "routes/bus": typeof import("./app/routes/bus.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/notifications": typeof import("./app/routes/notifications.tsx");
  "routes/trips": typeof import("./app/routes/trips.tsx");
  "routes/trip/history": typeof import("./app/routes/trip/history.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
};