// Mock Student Data
// Sample data for testing and development

import type { Student } from './types';

export const mockStudents: Student[] = [
  {
    id: '1',
    studentId: 'STU001',
    name: 'Emma Johnson',
    grade: '10',
    status: 'active',
    busRoute: 'Route A - North',
    parentName: 'Michael Johnson',
    parentPhone: '+1 (555) 123-4567',
    parentEmail: 'michael.johnson@email.com',
    address: '123 Maple Street, Springfield',
    joinDate: '2023-09-01',
    emergencyContact: '+1 (555) 987-6543',
    medicalInfo: 'No known allergies',
  },
  {
    id: '2',
    studentId: 'STU002',
    name: 'Liam Smith',
    grade: '9',
    status: 'active',
    busRoute: 'Route B - South',
    parentName: 'Sarah Smith',
    parentPhone: '+1 (555) 234-5678',
    parentEmail: 'sarah.smith@email.com',
    address: '456 Oak Avenue, Springfield',
    joinDate: '2023-09-01',
    emergencyContact: '+1 (555) 876-5432',
  },
  {
    id: '3',
    studentId: 'STU003',
    name: 'Olivia Williams',
    grade: '11',
    status: 'active',
    busRoute: 'Route A - North',
    parentName: 'James Williams',
    parentPhone: '+1 (555) 345-6789',
    parentEmail: 'james.williams@email.com',
    address: '789 Pine Road, Springfield',
    joinDate: '2023-08-28',
    medicalInfo: 'Asthma - carries inhaler',
  },
  {
    id: '4',
    studentId: 'STU004',
    name: 'Noah Brown',
    grade: '10',
    status: 'inactive',
    busRoute: 'Route C - East',
    parentName: 'Emily Brown',
    parentPhone: '+1 (555) 456-7890',
    parentEmail: 'emily.brown@email.com',
    address: '321 Elm Street, Springfield',
    joinDate: '2023-09-05',
    notes: 'Temporarily inactive - family vacation',
  },
  {
    id: '5',
    studentId: 'STU005',
    name: 'Ava Davis',
    grade: '12',
    status: 'active',
    busRoute: 'Route B - South',
    parentName: 'Robert Davis',
    parentPhone: '+1 (555) 567-8901',
    parentEmail: 'robert.davis@email.com',
    address: '654 Birch Lane, Springfield',
    joinDate: '2022-09-01',
  },
  {
    id: '6',
    studentId: 'STU006',
    name: 'Ethan Martinez',
    grade: '9',
    status: 'active',
    busRoute: 'Route D - West',
    parentName: 'Maria Martinez',
    parentPhone: '+1 (555) 678-9012',
    parentEmail: 'maria.martinez@email.com',
    address: '987 Cedar Court, Springfield',
    joinDate: '2023-09-01',
  },
  {
    id: '7',
    studentId: 'STU007',
    name: 'Sophia Garcia',
    grade: '11',
    status: 'active',
    busRoute: 'Route A - North',
    parentName: 'Carlos Garcia',
    parentPhone: '+1 (555) 789-0123',
    parentEmail: 'carlos.garcia@email.com',
    address: '159 Willow Way, Springfield',
    joinDate: '2022-09-05',
    medicalInfo: 'Lactose intolerant',
  },
  {
    id: '8',
    studentId: 'STU008',
    name: 'Mason Rodriguez',
    grade: '10',
    status: 'active',
    busRoute: 'Route C - East',
    parentName: 'Linda Rodriguez',
    parentPhone: '+1 (555) 890-1234',
    parentEmail: 'linda.rodriguez@email.com',
    address: '753 Spruce Street, Springfield',
    joinDate: '2023-09-01',
  },
  {
    id: '9',
    studentId: 'STU009',
    name: 'Isabella Lopez',
    grade: '12',
    status: 'active',
    busRoute: 'Route B - South',
    parentName: 'Juan Lopez',
    parentPhone: '+1 (555) 901-2345',
    parentEmail: 'juan.lopez@email.com',
    address: '246 Ash Boulevard, Springfield',
    joinDate: '2022-08-30',
  },
  {
    id: '10',
    studentId: 'STU010',
    name: 'James Wilson',
    grade: '9',
    status: 'inactive',
    busRoute: 'Route D - West',
    parentName: 'Patricia Wilson',
    parentPhone: '+1 (555) 012-3456',
    parentEmail: 'patricia.wilson@email.com',
    address: '135 Poplar Place, Springfield',
    joinDate: '2023-09-01',
    notes: 'Inactive - transferred to another school',
  },
  {
    id: '11',
    studentId: 'STU011',
    name: 'Charlotte Anderson',
    grade: '11',
    status: 'active',
    busRoute: 'Route A - North',
    parentName: 'Thomas Anderson',
    parentPhone: '+1 (555) 123-7890',
    parentEmail: 'thomas.anderson@email.com',
    address: '468 Fir Avenue, Springfield',
    joinDate: '2022-09-05',
  },
  {
    id: '12',
    studentId: 'STU012',
    name: 'Benjamin Taylor',
    grade: '10',
    status: 'active',
    busRoute: 'Route C - East',
    parentName: 'Jennifer Taylor',
    parentPhone: '+1 (555) 234-8901',
    parentEmail: 'jennifer.taylor@email.com',
    address: '802 Chestnut Drive, Springfield',
    joinDate: '2023-09-01',
    emergencyContact: '+1 (555) 765-4321',
  },
  {
    id: '13',
    studentId: 'STU013',
    name: 'Amelia Thomas',
    grade: '12',
    status: 'active',
    busRoute: 'Route B - South',
    parentName: 'David Thomas',
    parentPhone: '+1 (555) 345-9012',
    parentEmail: 'david.thomas@email.com',
    address: '579 Maple Court, Springfield',
    joinDate: '2022-09-01',
  },
  {
    id: '14',
    studentId: 'STU014',
    name: 'Lucas Jackson',
    grade: '9',
    status: 'active',
    busRoute: 'Route D - West',
    parentName: 'Michelle Jackson',
    parentPhone: '+1 (555) 456-0123',
    parentEmail: 'michelle.jackson@email.com',
    address: '913 Oak Terrace, Springfield',
    joinDate: '2023-09-01',
  },
  {
    id: '15',
    studentId: 'STU015',
    name: 'Mia White',
    grade: '11',
    status: 'active',
    busRoute: 'Route A - North',
    parentName: 'Christopher White',
    parentPhone: '+1 (555) 567-1234',
    parentEmail: 'christopher.white@email.com',
    address: '246 Pine Circle, Springfield',
    joinDate: '2022-09-05',
    medicalInfo: 'Epilepsy - emergency protocol on file',
  },
];

export function getStudentById(id: string): Student | undefined {
  return mockStudents.find((student) => student.id === id);
}

export function getStudentsByGrade(grade: string): Student[] {
  return mockStudents.filter((student) => student.grade === grade);
}

export function getStudentsByBusRoute(route: string): Student[] {
  return mockStudents.filter((student) => student.busRoute === route);
}

export function getActiveStudents(): Student[] {
  return mockStudents.filter((student) => student.status === 'active');
}

export function getInactiveStudents(): Student[] {
  return mockStudents.filter((student) => student.status === 'inactive');
}

